# Generated by Django 3.2.3 on 2021-05-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210525_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trades',
            name='priceB',
        ),
        migrations.RemoveField(
            model_name='trades',
            name='priceS',
        ),
    ]
