# Generated by Django 3.2.3 on 2021-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210525_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='priceB',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trades',
            name='priceS',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
