# Generated by Django 3.2.3 on 2021-05-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210525_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='spent',
            field=models.IntegerField(blank=True),
        ),
    ]
