# Generated by Django 3.2.3 on 2021-05-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_trades_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='priceB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='priceS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='spent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
