# Generated by Django 3.2.3 on 2021-05-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210525_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='priceB',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='priceS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='spent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
