# Generated by Django 3.2.3 on 2021-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_trades_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
