# Generated by Django 3.2.3 on 2021-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_trades_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='test',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
